export const GET_PROCESSES = ""
export const GET_STEPSNUMBER = ""

export const GET_ALL_FARMS = "GET_ALL_FARMS"
export const GET_WEIGHT_UNIT = "GET_WEIGHT_UNIT"
export const GET_AREA_UNIT = "GET_AREA_UNIT"
export const GET_CERTIFYCATE_OF_LANDS = "GET_CERTIFYCATE_OF_LANDS"

export const ADD_FARMSEASION = "ADD_FARMSEASION"