import React from 'react'

const vi = {
  /**
   * Server localization
   */
  server_resetkey_invalid: 'Mã OTP không chính xác',
  server_TOKEN_EXPIRED: 'Hết phiên đăng nhập',
  server_email_already_used: 'Email hoặc Số điện thoại đã được sử dụng để đăng ký tài khoản',
  server_error_validation: 'Email hoặc Số điện thoại không hợp lệ',
  server_user_notfound: 'Tài khoản không tồn tại',
  server_can_not_connect: 'Không thể kết nối đến máy chủ!!!',
  server_maintenance: 'Máy chủ đang bảo trì',
  server_user_login_invalid: 'Tài khoản đăng nhập hoặc mật khẩu không chính xác',
  server_user_not_activated: 'Tài khoản chưa được kích hoạt',

  /**
   * global validation
   */
  phone_or_email_required: 'Vui lòng nhập email hoặc số điện thoại',
  invalid_email: 'Email không hợp lệ',
  email_required: 'Vui lòng nhập Email',
  password_not_matched: 'Mật khẩu không trùng khớp',
  invalid_email_or_phone: 'Email/Số điện thoại không hợp lệ',
  required: 'Vui lòng nhập thông tin',
  password_required: 'Vui lòng nhập mật khẩu',
  more_than_zero: 'Giá trị phải lớn hơn 0',
  invalid_password: 'Mật khẩu từ 6 ký tự trở lên',
  max_length: 'Tối đa {max} ký tự',
  /**
   * Client localization
   */
  home: 'Trang chủ',
  login: 'Đăng nhập',
  login_anotation: 'Đăng nhập để sử dụng các ứng dụng trong nền tảng',
  login_placeholder: 'Email hoặc số điện thoại',
  password: 'Mật khẩu',
  reenter_password: 'Nhập lại mật khẩu',
  forgot_password: 'Quên mật khẩu?',
  register_an_account: 'Đăng ký tài khoản?',
  intro: '<p>AgriSys là nền tảng quản lý trang trại dành cho nông dân hoặc nhà sản xuất được phát triển bởi công ty công nghệ nông nghiệp, bao gồm hệ thống các ứng dụng hỗ trợ nông dân từ trang trại đến thương mại hoá sản phẩm. Người dùng có thể cài đặt từng ứng dụng để sử dụng hoặc gỡ cài đặt nếu không sử dụng.</p><p>Cảm ơn đã đồng hành cùng AgriTech. Mọi thông tin hoặc thắc mắc vui lòng gửi về địa chỉ email hotro@global-agritech.</p>',
  copy_right: 'Copyright @2020 by AgriTech Inc.',
  recovery: 'Lấy lại mật khẩu',
  recovery_anotation: 'Theo chỉ dẫn dưới đây để lấy lại mật khẩu tài khoản',
  continue: 'Tiếp tục',
  back: 'Quay lại',
  wanna_login: 'Đăng nhập?',
  email_otp_sent: 'Chúng tôi đã gửi 6 ký tự để xác thực tài khoản chủ thể tới email {email}',
  phone_otp_sent: 'Chúng tôi đã gửi 6 ký tự để xác thực tài khoản chủ thể tới số điện thoại {phone}',
  your_account: 'Tài khoản của bạn: {account}',
  completed: 'Hoàn thành',
  new_password: 'Mật khẩu mới',
  confirm_password: 'Nhập lại mật khẩu',
  register: 'Đăng ký',
  register_anotation: 'Vui lòng nhập vào thông tin theo mẫu dưới đây để đăng ký tài khoản',
  login_with_your_account: 'Đã có tài khoản? Đăng nhập',
  full_name: 'Họ và tên',
  phone: 'Số điện thoại',
  email: 'Email',
  choose_business_model: 'Chọn loại hình hoạt động',
  farming_business_placeholder: 'Vui lòng cung cấp thêm thông tin về trang trại hoặc doanh nghiệp',
  agree_agriSys_term: 'Đồng ý các điều khoản của AgriSys',
  completed_registry: '<p>Cảm ơn đã đăng ký tài khoản của AgriSys, chúng tôi sẽ liên hệ với quý khách sớm nhất để hoàn tất các thủ tục pháp lý để có tài khoản đăng nhập.</p><p>Trong thời gian đợi, vui lòng lưới qua các sàn giao dịch bán sỉ và bán lẻ cung cấp với AgriTech hoặc tải ứng dụng về máy để trải nghiệm.</p>',
  download: 'Tải ứng dụng',
  setup_profile: 'Cài đặt thông tin hồ sơ',
  personal_info: 'Thông tin cá nhân',
  farming_experience: 'Kinh nghiệm canh tác',
  certificate: 'Giấy chứng nhận',
  birthday_placeholder: 'Ngày tháng năm sinh',
  level: 'Trình độ',
  career: 'Ngành nghề',
  identification_documents: 'Giấy tờ tuỳ thân',
  address: 'Địa chỉ',
  degree: 'Bằng cấp',
  income: 'Thu nhập',
  family: 'Gia đình',
  bank: 'Ngân hàng',
  document_type: 'Loại giấy tờ',
  identity_number: 'Số',
  date_of_issue: 'Ngày cấp',
  place_of_issue: 'Nơi cấp',
  identification: 'Định danh',
  kyc: 'KYC',
  update: 'Cập nhật',
  close: 'Đóng',
  add_row: 'Thêm dòng',
  address_type: 'Loại địa chỉ',
  country: 'Quốc gia',
  city_or_province: 'Tỉnh/Thành phố',
  district: 'Quận/Huyện',
  postcode: 'Mã vùng',
  degree_of_the_school: 'Trường cấp',
  classification: 'Xếp loại',
  year_stared: 'Năm bắt đầu',
  year_ended: 'Năm kết thúc',
  field: 'Lĩnh vực',
  income_type: 'Loại',
  description: 'Mô tả',
  amount_of_money: 'Số tiền',
  bank_name: 'Ngân hàng',
  account_name: 'Tên tài khoản',
  account_number: 'Số tài khoản',
  bank_branch: 'Chi nhánh',
  relation_ship: 'Quan hệ',
  year_of_birth: 'Năm sinh',
  identity_papers: 'Giấy tờ tuỳ thân',
  ID_number: 'Số',
  start_date: 'Ngày bắt đầu',
  end_date: 'Ngày kết thúc',
  product_type: 'Loại sản phẩm',
  yield: 'Sản lượng',
  quanlity: 'Chất lượng',
  farming: 'Canh tác',
  unit: 'Đơn vị',
  more_description: 'Mô tả thêm chi tiết',
  history: 'Lịch sử',
  type_of: 'Loại hình',
  product: 'Sản phẩm',
  save: 'Lưu',
  cancel: 'Huỷ bỏ',
  skip_setup: 'Cài đặt sau',
  first_name: 'Họ',
  last_name: 'Tên',
  invalid_phone: 'Số điện thoại không hợp lệ',
  email_or_phone: 'Email/Số điện thoại',
  sent_OTP: 'Chúng tôi đã gởi mã kích hoạt đến tài khoản của bạn',
  activation_successful: 'Kích hoạt tài khoản thành công',
  active_account: 'Kích hoạt tài khoản',
  active_account_anotation: 'Theo chỉ dẫn dưới đây để kích hoạt tài khoản',
  reset_password_successful: 'Cập nhật tài khoản thành công',
  login_failed: 'Đăng nhập không thành công',
  expiration_date: 'Ngày hết hạn',
  certificate_type: 'Loại chứng nhận',
  issued_by: 'Cấp bởi',
  endorsed: 'Đã chứng thực',
  not_authenticated: 'Chưa chứng thực',
  require_firstName: 'Vui lòng nhập Họ',
  require_lastName: 'Vui lòng nhập Tên',
  vietnam: 'Việt Nam',
  completed_setup: 'Hoàn thành cài đặt',
  completed_setup_description: 'Cảm ơn đã hoàn thành thông tin cần thiết để có thể sử dụng hệ thống quản lý nông trại.Cảm ơn đã hoàn thành thông tin cần thiết để có thể sử dụng hệ thống quản lý nông trại.Cảm ơn đã hoàn thành thông tin cần thiết để có thể sử dụng hệ thống quản lý nông trại.',
  start_date_greater_than_end_date: 'Ngày kết thúc phải lớn hơn ngày bắt đầu',
  issue_date_greater_than_expired_date: 'Ngày hết hạn phải lớn hơn ngày cấp',
  update_profile_successful: 'Cập nhật thông tin tài khoản thành công',
  invalid_format: 'Nhập sai định dạng',
  profiles_management: 'Quản lý hồ sơ',
  farmings_management: 'Quản lý nông trại',
  purchasing_management: 'Quản lý thu mua',
  goods_management: 'Quản lý hàng hoá',
  comercial_management: 'Quản lý thương mại',
  orders_management: 'Quản lý đơn hàng',
  partners_management: 'Quản lý đối tác',
  logistics_management: 'Quản lý kho vận',
  human_resources_management: 'Quản lý nhân sự',
  financial_management: 'Quản lý tài chính',
  messages_management: 'Tin nhắn',
  reports: 'Báo cáo thống kê',
  configuration: 'Cấu hình',
  dashboard: 'Tổng quan'

}

export default vi